#Example configuration for Black.

# NOTE: You have to use single-quotes strings in TOML for regular expressions.
# It's the equivalent of r-strings in Python. Multiline string are treated as 
# verbose regular expressions by Black. Use [ ] to denote a significant space 
# character.

[tool.black]
line-length = 110 
target-version = ['py36', 'py37', 'py38']
include = '\.pyi?$'
exclude = '''
/(
    \.eggs
  | \.git
  | \.hg
  | \.mypy_cache
  | \.tox
  | \.venv
  | _build
  | buck-out
  | build
  | dist
)/
'''
